name: Deploy to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: DISABLE_ESLINT_PLUGIN=true npm run build

      - name: Debug secrets
        run: |
          echo "VPS_HOST length: ${#{{ secrets.VPS_HOST }}}"
          echo "VPS_USERNAME length: ${#{{ secrets.VPS_USERNAME }}}"
          echo "VPS_SSH_KEY length: ${#{{ secrets.VPS_SSH_KEY }}}"
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USERNAME: ${{ secrets.VPS_USERNAME }}
          VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/avtometod
            git pull origin main
            npm ci --production
            npm run build
            sudo systemctl restart nginx